### ISSUE TITLE
Insert Images in flowchart

### ISSUE THREAD

**Issue by vikram-rawat** [knsv/mermaid#548]
How can I make a jpeg, png , gif as a NODE in flowchart.

Most of the time we need that for presentation purpose. 

Can We do that please. Please let me know

If not can you add that Please.....

**Comment by Krockema** [comment]
Normaly,

graph TD;
Dir((<img src='https://iconscout.com/ms-icon-310x310.png' width='40' />))

does the Trick. :-)

**Comment by lukasz-capala** [comment]
To get it work without API you need to use html special characters instead of direct chars like single quote, apostrophe, equal, etc.
`D-->X((&lt;img src&#61;&#39;/address/to/image.png&#39; width&#61;&#39;50&#39; /&gt;))`

**Comment by JUSTINMKAUFMAN** [comment]
Would it be possible to include a complete example flowchart where multiple modes display images?

**Comment by lennynyktyk** [comment]
I am able to do this use`mermaid-cli`, but through a convoluted way.

1. Use a div/span with a class
```
Phone(<span class=&quot;iphone-icon&quot;></span> My iPhone)-->(<span class=&quot;server-icon&quot;></span> My Server)
```
2. Then I created a CSS file with the class definitions:
```css
.iphone-icon { width:64px; height:64px; background: url(https://example.com/iphone-icon.png) no-repeat center center; }
.server-icon { width:64px; height:64px; background: url(https://example.com/server-icon.png) no-repeat center center; }
```
3. Then specify the `-C` option followed by the filesystem path to the CSS file when creating a SVG.
4. Then put the contents of the CSS file at the end of the `<style>` tag inside the SVG.
5. Finally you can convert it to PNG, JPG in necessary.

NOTE: All CSS URLs should be absolute web URLs if you plan to share the SVG.  Alternatively you could embed the icons in the CSS file using data-urls.
