### ISSUE TITLE
All <svg> elements in page are colored black

### ISSUE THREAD

**Issue by rhysd** [knsv/mermaid#584]
### Problem

I found a weird CSS rule in `<style>` element under `<svg id="mermaidChartXXX">` element as following.

```css
svg {
  color: rgb(0, 0, 0);
  font: normal normal normal normal 16px / normal "Hiragino Kaku Gothic ProN";
}
```

It colors all `<svg>` elements as black in an entire page overwriting other CSS rules.

### How to reproduce

1. Install mermaid with `$ npm install mermaid`
2. Open example page with `$ open node_modules/mermaid/dist/index.html`
3. Find `<svg id="mermaidChart1">` element under `<div class="mermaid">`
4. Check child `<style>` element's last CSS rule.

### Environment

Followings are my environment information:

- macOS 10.12.6
- Chrome 61.0.3163.100
- mermaid 7.1.0
