### ISSUE TITLE
Use yaml syntax

### ISSUE THREAD

**Issue by jgroom33** [knsv/mermaid#808]
The goal of this issue is to implement a data driven approach to the graph.

This approach will allow a structured syntax to handle layouts, layout properties, shapes, shape properties, lines and line properties.  Here's an example:

```yml
---
graph:
  layout: hierarchical
  properties:
    layout_direction: TD
    edge_weight: 100
    node_spacing: 100
  vertices:
    - name: myCircle
      shape: circle
      color: blue
    - name: myClass
      shape: class
      color: blue
      class_vars:
        - int foo
        - str bar
  edges:
    - A: myCircle
      Z: myClass
      A_end: circle
      Z_end: arrow
      line: dashed
      text: something interesting
```
 > mermaid code language would still be used.  The above codeblock is using yml to provide syntax highlighting
